# Generated by Django 5.0.6 on 2024-07-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_mechanic_skills_alter_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
