# Generated by Django 5.0.6 on 2024-07-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_bio_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_profile_complete',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
